services:
    web:
        build: 
            context: ./services/web
            dockerfile: Dockerfile.prod
        command: gunicorn -w 4 -b 0.0.0.0:42069 app:app
        environment:
            - FLASK_APP=
            - FLASK_ENV=
            
    nginx:
        build: 
            context: ./services
            dockerfile: ./nginx/Dockerfile.prod
        volumes:
            - user_prod:/www/user
            
    db:
        volumes:
            - mongo_prod:/data/db
            
            
volumes:
    user_prod:
    mongo_prod:
            
