services:
    web:
        build: ./services/web
        command: flask run --host=0.0.0.0 --port=42069 --debug
        volumes:
            - ./services/web:/www/app
        expose:
            - 42069
        environment:
            - FLASK_APP=app
            - FLASK_ENV=development
        depends_on:
            - db
            
    nginx:
        build: ./services/nginx
        ports:
            - 7007:80
        volumes:
            - ./services/web/static:/www/app/static
            - ./services/web/user_dev:/www/user
        depends_on:
            - web
            
    db:
        image: mongo:7.0.16
        volumes:
            - mongo_dev:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=secret
            
            
volumes:
    mongo_dev:
            
