services:
    web:
        build: ./services/web
        command: gunicorn --reload -w 4 -b 0.0.0.0:42069 app:app
        volumes:
            - ./services/web:/www/app
        expose:
            - 42069
        depends_on:
            - db
            
    nginx:
        build: ./services/nginx
        ports:
            - 7007:80
        depends_on:
            - web
            
    db:
        image: mongo:7.0.16
        volumes:
            - swal_mongo:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=secret
            
            
volumes:
    swal_mongo:
            
